theme: jekyll-theme-midnight
title: "Tri 2 Team Project"
description: "To be filled in"
gitorg: "https://github.com/Natalie-Beckwith/Tri2TeamProject"
description: "Also to be filled in"
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one